package edu.quinnipiac.ser210.harrypottercharacters.data;

import android.os.Parcel;
import android.os.Parcelable;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.Serializable;

/**
 * @author Thomas Kwashnak
 * Uses a Parcelable interface in order to allow storing and retrieving of this object in a Bundle
 */
public class Character implements Parcelable {

    private final String name;
    private final String[] alternateNames;
    private final String species;
    private final String gender;
    private final String house;
    private final String dateOfBirth;
    private final int yearOfBirth;
    private final boolean wizard;
    private final String ancestry;
    private final String eyeColour;
    private final String hairColour;
    private final Wand wand;
    private final String patronus;
    private final boolean hogwartsStudent;
    private final boolean hogwartsStaff;
    private final String actor;
    private final String[] alternateActors;
    private final boolean alive;
    private final String image;

    /**
     * Reads a Character from a json object
     * @param jsonObject
     * @throws JSONException
     */
    public Character(JSONObject jsonObject) throws JSONException {
        name = jsonObject.getString("name");
        alternateNames = convertJSONtoStringArray(jsonObject.getJSONArray("alternate_names"));
        species = jsonObject.getString("species");
        gender = jsonObject.getString("gender");
        house = jsonObject.getString("house");
        dateOfBirth = jsonObject.getString("dateOfBirth");
        int yearOfBirth = 0;
        try {
            yearOfBirth = jsonObject.getInt("yearOfBirth");
        } catch(Exception e) {}
        this.yearOfBirth = yearOfBirth;
        wizard = jsonObject.getBoolean("wizard");
        ancestry = jsonObject.getString("ancestry");
        eyeColour = jsonObject.getString("eyeColour");
        hairColour = jsonObject.getString("hairColour");
        wand = new Wand(jsonObject.getJSONObject("wand"));
        patronus = jsonObject.getString("patronus");
        hogwartsStudent = jsonObject.getBoolean("hogwartsStudent");
        hogwartsStaff = jsonObject.getBoolean("hogwartsStaff");
        actor = jsonObject.getString("actor");
        alternateActors = convertJSONtoStringArray(jsonObject.getJSONArray("alternate_actors"));
        alive = jsonObject.getBoolean("alive");
        image = jsonObject.getString("image").replace("http://","https://");
    }

    /**
     * Reads a Character from a Parcel
     * @param in
     */
    protected Character(Parcel in) {
        name = in.readString();
        alternateNames = in.createStringArray();
        species = in.readString();
        gender = in.readString();
        house = in.readString();
        dateOfBirth = in.readString();
        yearOfBirth = in.readInt();
        wizard = in.readByte() != 0;
        ancestry = in.readString();
        eyeColour = in.readString();
        hairColour = in.readString();
        wand = in.readParcelable(Wand.class.getClassLoader());
        patronus = in.readString();
        hogwartsStudent = in.readByte() != 0;
        hogwartsStaff = in.readByte() != 0;
        actor = in.readString();
        alternateActors = in.createStringArray();
        alive = in.readByte() != 0;
        image = in.readString();
    }

    /**
     * Autogenerated Creator that manages both creation of Characters and Character Arrays
     */
    public static final Creator<Character> CREATOR = new Creator<Character>() {
        @Override
        public Character createFromParcel(Parcel in) {
            return new Character(in);
        }

        @Override
        public Character[] newArray(int size) {
            return new Character[size];
        }
    };

    /**
     * Converts a JSON array to a String array
     * @param array
     * @return
     * @throws JSONException
     */
    private static String[] convertJSONtoStringArray(JSONArray array) throws JSONException {
        String[] strings = new String[array.length()];
        for(int i = 0; i < strings.length; i++) {
            strings[i] = array.getString(i);
        }
        return strings;
    }

    public String getName() {
        return name;
    }

    public String[] getAlternateNames() {
        return alternateNames;
    }

    public String getSpecies() {
        return species;
    }

    public String getGender() {
        return gender;
    }

    public String getHouse() {
        return house;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public int getYearOfBirth() {
        return yearOfBirth;
    }

    public boolean isWizard() {
        return wizard;
    }

    public String getAncestry() {
        return ancestry;
    }

    public String getEyeColour() {
        return eyeColour;
    }

    public String getHairColour() {
        return hairColour;
    }

    public Wand getWand() {
        return wand;
    }

    public String getPatronus() {
        return patronus;
    }

    public boolean isHogwartsStudent() {
        return hogwartsStudent;
    }

    public boolean isHogwartsStaff() {
        return hogwartsStaff;
    }

    public String getActor() {
        return actor;
    }

    public String[] getAlternateActors() {
        return alternateActors;
    }

    public boolean isAlive() {
        return alive;
    }

    public String getImage() {
        return image;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Stores the Character to a Parcel
     * @param parcel
     * @param i
     */
    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(name);
        parcel.writeStringArray(alternateNames);
        parcel.writeString(species);
        parcel.writeString(gender);
        parcel.writeString(house);
        parcel.writeString(dateOfBirth);
        parcel.writeInt(yearOfBirth);
        parcel.writeByte((byte) (wizard ? 1 : 0));
        parcel.writeString(ancestry);
        parcel.writeString(eyeColour);
        parcel.writeString(hairColour);
        parcel.writeParcelable(wand, i);
        parcel.writeString(patronus);
        parcel.writeByte((byte) (hogwartsStudent ? 1 : 0));
        parcel.writeByte((byte) (hogwartsStaff ? 1 : 0));
        parcel.writeString(actor);
        parcel.writeStringArray(alternateActors);
        parcel.writeByte((byte) (alive ? 1 : 0));
        parcel.writeString(image);
    }

    public String toString() {
        StringBuilder s = new StringBuilder();

        s.append(name).append("\n");
        if(alternateNames != null && alternateNames.length > 0) {
            s.append("Also known as: ");
            for(int i =0; i < alternateNames.length; i++) {
                if(i != 0) {
                    s.append(", ");
                }
                s.append(alternateNames[i]);
            }
            s.append("\n");
        }
        s.append("Played by: ").append(actor);
        if(alternateActors != null && alternateActors.length > 0) {
            s.append("Also played by: ");
            for(int i =0; i < alternateActors.length; i++) {
                if(i != 0) {
                    s.append(", ");
                }
                s.append(alternateActors[i]);
            }
        }

        return s.toString();
    }
}
